### ISSUE TITLE
Running sample gives me just a green screen

### ISSUE THREAD

**Issue by matkoniecz** [korlibs/korge-samples#2]
`./gradlew :sample-box2d:runJvm` loads for a second or two and show green screen

Is it intentional? I thought that there will be something more

![Selection_007](https://user-images.githubusercontent.com/899988/72225386-3a1b1f80-3585-11ea-911e-a9bcca972a00.png)

Sadly, there is no screenshot in the readme  so I am not sure what is expected to happen

**Comment by soywiz** [comment]
It is not intentional. Which linux distro/computer specs are you using?
You can use JS in the meantime: `./gradlew :sample-box2d:runJs`

![Captura de pantalla 2020-01-12 a las 22 22 04](https://user-images.githubusercontent.com/570848/72225816-0d1d3b80-358a-11ea-8e47-05bd3c217f4c.png)

**Comment by matkoniecz** [comment]
I went through series of upgrades of various software, and now that I retried it works ax expected.
