### ISSUE TITLE
Mask not working on MacOS

### ISSUE THREAD

**Issue by mayankmkh** [korlibs/korge-samples#37]
I tried running mask sample but the mask is not working on JVM, native, and iOS. It works fine on Js and Android though.

**Device**: MacBook Pro (16-inch, 2019)
**OS**: macOS Catalina version 10.15.7

**Comment by mayankmkh** [comment]
You already fixed it 😮. That was fast. Thanks!

**Comment by soywiz** [comment]
Yeah :) , the stencil bits were not specified, and the default was 0, while for this to work it should be the standard of 8

**Comment by mayankmkh** [comment]
I tried running mask sample with KorGE 2.0.5.1, it's working on native now 🙂 but not on ios or JVM. Adding some more details.

Java env
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```

ios
```
Device: iPhone 8 simulator
OS: iOS 14
```

**Comment by soywiz** [comment]
This was fixed sometiem ago
