### ISSUE TITLE
gradle.properties requires "android.useAndroidX=true" in order for project to build in IntelliJ CE 2020.3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by exertionriver** [korlibs/korge-samples#40]
After cloning current repo.

Thank you,
Ian

**Comment by soywiz** [comment]
Why do you believe this? Did you get an error indicating that?

I mean, supposedly this repo is configured to use an Android indirect, that creates a separate project in `build/platforms/android`, that should include that `android.useAndroidX=true` already in its generated `gradle.properties`:

https://github.com/korlibs/korge-plugins/blob/120f263fb5c7a32c29acd2db37d159afa196b69d/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/targets/android/Android.kt#L285

**Comment by exertionriver** [comment]
Hi @soywiz, thanks for your reply.

I restored altered project files, deleted the .gradle cache, let gradle reindex, and rebuilt. Here is the output:

```
Could not determine the dependencies of task ':integrations:android:app:lintVitalRelease'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.core:core:1.3.2...
```

I hadn't seen 'lintVitalRelease' at the time I reported the issue.

What do you think..?

Thank you,
Ian

**Comment by soywiz** [comment]
`settings.gradle` was including all the folders with a `build.gradle`, at some point the integrations folder was added. But that root project shouldn't include the integrations/app module.

Can you try again? I hope it is fixed, but might not be the case. Feel free to reopen if it is not the case

**Comment by exertionriver** [comment]
Issue appears to go away after pulling and rebuilding. Thanks..!
