### ISSUE TITLE
compileKotlinLinuxX64 task fails with "Could not find "org.jetbrains.kotlinx:atomicfu-cinterop-interop"" in IntelliJ CE 2020.3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by exertionriver** [korlibs/korge-samples#41]
After cloning current repo.

Further details:
Could not find "org.jetbrains.kotlinx:atomicfu-cinterop-interop" in [.../korge-samples, .../.konan/klib, .../.konan/kotlin-natic-rebuilt-linux-1.4.30/klib/common, .../.konan/kotlin-native-prebuilt-linux-1.4.30/klib/platform/linux_x64].

Thank you,
Ian

**Comment by exertionriver** [comment]
same error appears when running 'runNative' Task from command line, e.g. "./gradlew --no-daemon :sample:box2d:runNative"

**Comment by soywiz** [comment]
Hey @exertionriver , can you indicate the output of `java -version` ?

**Comment by exertionriver** [comment]
Hi @soywiz, thanks for your reply.

```java -version``` shows
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
also ```./gradlew -v :sample:box2d:runNative``` shows
```
Gradle 6.8.2
Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (Ubuntu 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OS:           Linux 5.4.0-65-generic amd64
```
Any ideas..?

Thank you,
Ian

**Comment by exertionriver** [comment]
Also seeing this same error when attempting to rebuild [hello-world](https://github.com/korlibs/korge-hello-world) or run at least one runNative* task. runJvm works fine.

Thank you,
Ian

**Comment by soywiz** [comment]
Can you try to select java 8 instead of java 11? Just in case it is related to the java version?

**Comment by soywiz** [comment]
Something you can try:

Delete:
```
~/.gradle/* -- except ~/.gradle/gradle.properties (in the case it exists)
~/.m2/repositories/*
~/.konan/*
```

In the case some file got corrupted or something. I just tried on windows that task and seems to work, and the last time I tried ubuntu/x64 worked too:

```
C:\Users\soywi\projects\korlibs\korge-samples>gradlew --no-daemon :sample:box2d:runNative
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.8.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
Configuration on demand is an incubating feature.

> Task :sample:box2d:compileKotlinJvm
...
> Task :sample:box2d:compileKotlinMingwX64
...
> Task :sample:box2d:runNativeMingwX64Release
Korui[0]
CanvasApplicationEx.IN[0]
....
```

Can you try to delete those folders and try again? If that doesn't help, I could try again on linux and see if it is working.

**Comment by exertionriver** [comment]
Hi @soywiz,

Looks like something cleared itself up with deleting these folders and letting them get rebuild.

running ```gradlew --no-daemon :sample:box2d:runNative``` now works and 

running task ```runNative``` within ```korge-hello-world``` now works.

Also, fwiw switching to Java 15.0.2, rebuilding, and running task ```runNative``` within ```korge-hello-world``` now works.

Thanks for your help. Apologies for the fire-drill..! :-)

Thank you,
Ian

**Comment by soywiz** [comment]
No problem! Glad it works for you now :)
