### ISSUE TITLE
ominous warning: "An illegal reflective access operation has occurred" when running Task :sample:box2d:runJvm from command line on Ubuntu 20.04

### ISSUE THREAD

**Issue by exertionriver** [korlibs/korge-samples#42]
After cloning current repo. Task runs successfully (window appears and boxes fall on box)

Details: 

"WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.soywiz.korgw.internal.MicroDynamic (file:.../.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.korgw/korgw-jvm/2.0.7/a2918f7a4ad5d1b20f1791b9b52c07a897953970/korgw-jvm-2.0.7.jar) to method sun.awt.AWTAccessor.getComponentAccessor()
WARNING: Please consider reporting this to the maintainers of com.soywiz.korgw.internal.MicroDynamic
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release"

Thank you,
Ian

**Comment by soywiz** [comment]
Hey @exertionriver , thanks for your report.
Unfortunately, this is a current limitation I don't know how to handle right now. For more details, check this issue: https://github.com/korlibs/korge/issues/326

Going to close this issue. If you have some ideas, on how to fix this, please, feel free to reopen it and comment :)
