### ISSUE TITLE
Sample s3d utils.kt unsolved reference and type mismatch

### ISSUE THREAD

**Issue by monyettenyom** [korlibs/korge-samples#61]
Update: I've cloned the repository again and I will try today to understand the source Codes, so I'm closing this issue. Thanks for reading.   

Hi,

so I had downloaded a sample called "s3d", with main.kt and utils.kt copy pasted. I tried to build the project based on hallo-world-korge project and I received these two error message:
<img width="947" alt="Bildschirmfoto 2022-09-05 um 10 20 19" src="https://user-images.githubusercontent.com/58295352/188403853-be23e9eb-22ed-454b-be93-bcc153d86d45.png">

<img width="959" alt="Bildschirmfoto 2022-09-05 um 10 29 35" src="https://user-images.githubusercontent.com/58295352/188404643-d42b8df4-c8eb-409d-9198-11831669e15b.png">

For the first error, I chose:

<img width="893" alt="Bildschirmfoto 2022-09-05 um 10 20 36" src="https://user-images.githubusercontent.com/58295352/188405581-50a7c9ec-2b4d-4c2d-b336-afc9939d044c.png">

and didn't work:

<img width="791" alt="Bildschirmfoto 2022-09-05 um 10 20 48" src="https://user-images.githubusercontent.com/58295352/188405728-923dc42c-b92c-4bc6-af09-4fdb6b6606c2.png">

My second attempt was this:

<img width="450" alt="Bildschirmfoto 2022-09-05 um 10 42 36" src="https://user-images.githubusercontent.com/58295352/188407338-8bb966b1-9a77-46d4-9eeb-6dac9790bcef.png">

and I have received this error message:

<img width="960" alt="Bildschirmfoto 2022-09-05 um 10 43 54" src="https://user-images.githubusercontent.com/58295352/188407585-00540801-eba3-480c-b461-bd6a266eee19.png">

What did I do wrong? Please help. Thanks.

PS: I'm using KorGe Version 3.0.0 and Kotlin 1.7.20 on IDE IntelliJ Ultimate in an M1 MacBook Pro.

**Comment by soywiz** [comment]
Graphics now require:

```kotlin
graphics {
  updateShapes {
    // ...
  }
}
```
